version: "3.9"

services:

  db:
    image: postgres:14.2-bullseye
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./db/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=healenium
      - POSTGRES_USER=healenium_user
      - POSTGRES_PASSWORD=YDk2nmNs4s9aCP6K
    networks:
      - healenium

  healenium:
    image: healenium/hlm-backend:3.2.2
    container_name: healenium
    restart: on-failure
    ports:
      - "7878:7878"
    links:
      - db
    environment:
      - SPRING_CONTAINER_NAME=healenium
      - SPRING_POSTGRES_DB=healenium
      - SPRING_POSTGRES_USER=healenium_user
      - SPRING_POSTGRES_PASSWORD=YDk2nmNs4s9aCP6K
      - SPRING_POSTGRES_URL=jdbc:postgresql://db:5432/healenium?currentSchema=healenium
    networks:
      - healenium

  selector-imitator:
    image: healenium/hlm-selector-imitator:1.1
    container_name: selector-imitator
    restart: on-failure
    ports:
      - "8000:8000"
    networks:
      - healenium

  hlm-proxy:
    image: healenium/hlm-proxy:0.2.5.1
    container_name: hlm-proxy
    restart: on-failure
    ports:
      - "8085:8085"
    environment:
      - "recovery-tries=1"
      - "score-cap=.6"
      - "heal-enabled=true"
    networks:
      - healenium

  selenoid:
    image: healenium/hlm-selenoid:0.1.0
    container_name: hlm-selenium-webview
    restart: on-failure
    ports:
      - "4444:4444"
    environment:
      - "PROXY_CONTAINER_NAME=hlm-proxy"
    volumes:
      - .:/etc/selenoid/:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: ["-container-network", "healenium"]
    networks:
      - healenium

  selenoid-ui:
    image: aerokube/selenoid-ui:1.10.4
    container_name: hlm-selenium-webview-ui
    restart: on-failure
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://hlm-selenium-webview:4444"]
    networks:
      - healenium

networks:
  healenium:
    name: healenium